### ISSUE TITLE
App crash when presenting login modal - SwiftUI

### ISSUE THREAD

**Issue by AchidFarooq** [sumup/sumup-ios-sdk#100]
Hi,

We have a strange crash when we start a payment when user is not signed in to SumUp.

Flow:
- start a sumup payment
- sumup opens sign in modal screen

Now is the strange part - if we have an ipad with an external keyboard everything works fine.
But if we have an iPad with no external keyboard where the native keyboard pops up - to fill in email and password - crash! (See crash report below)

`2020-10-28 14:14:09.363083+0100 Staging iPad App[2878:1379274] [error] precondition failure: no graph: 6984524
AttributeGraph precondition failure: no graph: 6984524.`

So as soon as the native keyboard opens the crash happens.
Do you guys have an idea what this can be?

Xcode version 12.1
Sumup SDK version 4.0.0

**Comment by andraskadar** [comment]
Hi @AchidFarooq, thanks for reaching out!

In order to help you solve this, can you provide a minimalistic, sample app for us, where it is reproducible?
Is this happening only when using SwiftUI only applications, or how is that related (in the issue title)?
It might not be related, but to be complete, on which iPad and iOS version is this happening?

**Comment by AchidFarooq** [comment]
After a few pod deinits and reinstalls it worked suddenly. Thanks for a fast reply @andraskadar
