### ISSUE TITLE
Permanent bluetooth connectivity of Sumup Air

### ISSUE THREAD

**Issue by DrSmax** [sumup/sumup-ios-sdk#112]
Hello all
I am very new here and not even sure if I am in the right place for my request..., if not, I apologise in advance!
I'm trying to find a satisfactory answer to Bluetooth connectivity (Sumup Air) and so far I'm getting nowhere.... 
My problem:
We work in our small shop with two iPads as PoS. We have also bought 2 Sumup Air terminals for this purpose. Unlike all the other Bluetooth devices (barcode scanners, receipt printers...), the "Airs" cannot be stored in the "list of known Bluetooth connections" of the respective iPads.
A connection is established during the payment process, must be confirmed with the code and then also appears in the Bluetooth list of the corresponding iPad. However, as soon as the device goes into standby mode, the Bluetooth connection is terminated. The next time a payment is made, it is a lottery with which of the two Airs the iPad wants to pair... 
Find the right device, enter the number again if necessary.... - Is there no other way?
Why can't a terminal be permanently paired with a PoS iPad - just like you can with the other devices? Or deactivate the stndby?
I imagine a beer garden where the waiters run wildly through the area to find the right terminal...
Thank you very much and best regards
Smax

**Comment by JullianSU** [comment]
Good afternoon,

In order to be able to assist you regarding the issue that you are
referring to with the connectivity issues, we kindly ask you to let us know
what kind of integration are you using: SDK
<https://developer.sumup.com/docs/terminal-sdk/> or API Switch
<https://developer.sumup.com/docs/terminal-api/>.

Please note that if you are using SumUp's SDK, you can prepare the card
reader in advance by following the instructions detailed here
<https://github.com/sumup/sumup-android-sdk#3-prepare-the-sumup-card-terminal-in-advance>
for
Android and here
<https://github.com/sumup/sumup-ios-sdk#prepare-the-sumup-card-terminal-in-advance>
for iOS.

However, we strongly suggest contacting our troubleshooting team via
me.sumup.com/support since they will be able to assist you with any
Bluetooth connectivity issue.

Kind regards,

*Tatiana Lizarazo*
Technical Implementation Associate
Sales & Partnerships

SumUp. A better way to get paid.

***@***.*** ***@***.***>* | sumup.com

Facebook <http://facebook.com/sumup.co.uk> | Twitter
<http://twitter.com/sumup>

SumUp Services GmbH • Koppenstraße 8 • D-10243 Berlin
Amtsgericht Berlin-Charlottenburg HRB 142523 B • Geschäftsführer:
Marc-Alexander
Christ

This email may contain confidential and/or privileged information. If you
are not the intended recipient - or have received this email in error -
please notify the sender immediately and delete this email. Any
unauthorised copying, disclosure or distribution of the material in this
email is strictly forbidden.

**Comment by jadeburton-sumup** [comment]
As this issue is 3 years old I am closing the ticket. If it is still a problem please reach out to integration@sumup.com.
