### ISSUE TITLE
Checkout - We lost connection to the SumUp server

### ISSUE THREAD

**Issue by bebjakub** [sumup/sumup-ios-sdk#113]
Hello,
I'm using sumup-react-native-bridge and after choosing Card reader as payment method I receive a server connection error. 

screenshots: [1](https://user-images.githubusercontent.com/10927960/140536367-9aa38b92-1579-4b3f-bee6-5f1ef3dd3560.jpeg), [2](https://user-images.githubusercontent.com/10927960/140536359-ea4c2973-727a-45f8-b02a-3161f5dcca0b.jpeg) 
minimal [example](https://github.com/bebjakub/sumup-react-native-bridge/commit/e797dadac5fb7cadde2d45017e2a0dbad5add6a9)
[more info](https://github.com/azmicirit/sumup-react-native-bridge/issues/2)

What causes the error?
Thank you!

**Comment by danilkurkin1** [comment]
Had the same issue, I am doing Login with token. The problem was with setting application ID setup on me.sumup.com portal. I have debug, enterprise and appstore builds of the same app. Adding one com.example.myapp was workin for debug. Had to add ID's for com.example.myapp.enterprise & com.example.myapp.appstore. Issue was resilved by doing so.
Hope that helps

**Comment by bebjakub** [comment]
@danilkurkin1 Thanx. Yop, that was the problem :)
