### ISSUE TITLE
Login with Token Issue

### ISSUE THREAD

**Issue by RajaZahid** [sumup/sumup-ios-sdk#118]
Getting following error when trying to login with token:

Sorry, but we've experienced an unexpected error. Please try closing the app and logging in again, or contact our Support Team (quote: UKN-3J2LE)

**Comment by Vollkorn01** [comment]
+1

**Comment by tatianalizarazo** [comment]
Good morning,

Without much more information, please note that to use transparent authentication (login with a token with SDK), the access token should be generated using the grant type  [authorization_code](https://developer.sumup.com/docs/authorization/#authorization-code-flow).

Additionally, the authorisation request should have default (**transactions.history**, **user.app-settings**, **user.profile_readonly**) and **payments** scopes specified in order to get the access token working with the transparent authentication.

For any other query, please feel free to contact us via integration@sumup.com

Kind regards,

SumUp
