### ISSUE TITLE
Error when calling SumUpSDK.checkTapToPayAvailability()

### ISSUE THREAD

**Issue by cwimberger** [sumup/sumup-ios-sdk#157]
We're always getting an error when we try to call `checkTapToPayAvailibility()`.

The error simply says:

`Error Domain=com.sumup.sdk Code=102 "(null)"`

We've already requested the Tap to Pay on iPhone capability from Apple and added it to our app.
We're also using the latest version of the SDK. What are we doing wrong?

**Comment by jadeburton-sumup** [comment]
Hi @cwimberger, could you please share your Merchant ID or email login used for testing. Then I can check our backend logs. If you do not wish to share it here you can send it to integration@sumup.com, referencing this GH issue

**Comment by jadeburton-sumup** [comment]
Thanks @cwimberger, while we check logs, can you please check this:

Another integrator recently had this error and the underlying cause was that their Bundle build number and version were a format that was not accepted by our backend. Ensure the host app build number is non-zero and a positive number and there is nothing unusual about the host app version.

**Comment by cwimberger** [comment]
Hi @jadeburton-sumup, that was the problem!

I just changed our build number from "5.3.5" to "1" and now it works. Thanks!!

**Comment by jadeburton-sumup** [comment]
Great, happy to help
