### ISSUE TITLE
Resource bundles required to copy to the main app

### ISSUE THREAD

**Issue by ngoctr** [sumup/sumup-ios-sdk#34]
As SumUpSDK has not supported Cocapods yet, we had to make a local pod as a workaround. However, SumUpSDK requires its bundles to be copied to the main app and that's not a good idea for distributing a framework which should be self-contained. Can you please use [NSBundle bundleForClass:] so those bundles can live inside SumupSDK? More here https://developer.apple.com/reference/foundation/nsbundle/1417717-bundleforclass?language=objc
Thanks a lot.

**Comment by shagedorn** [comment]
The SumUp SDK is currently a static library + headers + resources. In case of the manual integration, the static library is compiled into your application and will not be a separate bundle at runtime, which is why the shared resources have to be bundled with your app as well.

We are currently working on official CocoaPods support. By default, CocoaPods builds a dynamic framework of all your pods, so the SumUp resources will live inside the pods framework, as does SumUp's code. To bundle the shared resources with the pods framework, the `podspec` file needs this:

```
s.resources = ["SumupSDK.embeddedframework/Resources/SMPSharedResources.bundle"]
```

I am not yet sure (but we will try it out before releasing our pod) what this line does when you disable dynamic frameworks for CocoaPods, but I would assume CocoaPods then adds the resources to your app directly, as you would do manually.

Unfortunately, `SumupSDK.embeddedframework/Resources/YTLibResources.bundle` *still* needs to be bundled with your app directly, as third party code we cannot change requires those resources to be in the main bundle. We are investigating better solutions as part of our CocoaPods integration.

As we still support iOS 6, we cannot support dynamic frameworks (without making it even more complicated by supplying two variants).

**Comment by ngoctr** [comment]
Hi @shagedorn Thanks for the reply. We dont use SumupSDK directly from our main app, we wrap SumupSDK inside a dynamic framework for our main app to use, so podspec.resources won't help as it puts the bundle into our framework, not the main app. Anyway, it's great to know SumupSDK will be supported via cocoapods. That'd be helpful.  Thanks a lot.

**Comment by shagedorn** [comment]
For the shared resources bundle, that is ok: It doesn't (or shouldn't) live in the main app if the SDK does not. So `podspec.resources` should do the right thing.

The only issue we currently see and are trying to solve are the YTLibResources, because they do need to be bundled with the main app directly. We will update this issue as we go.

**Comment by shagedorn** [comment]
As of [v3.0](https://github.com/sumup/sumup-ios-sdk/releases/tag/v3.0), we now officially support CocoaPods, and the above-mentioned `YTLibResources` bundle is not part of the SDK anymore. I assume this issue will be solved by those steps. Please re-open if it's still an issue.
